### ISSUE TITLE
Divide by zero error in old opponent probabilities when no old versions exist yet

### ISSUE THREAD

**Issue by Kaiyotech** [Rolv-Arild/rocket-learn#14]
I think this only occurs on new bots when there are no old versions yet. I think it just needs to check that an old version exists before trying to call the rand. I can work on it eventually, just wanted to make an issue so we don't lose track.

C:\Users\user\Code\Kaiyotech\ABAD\venv\lib\site-packages\rocket_learn\rollout_generator\redis_rollout_generator.py:490: RuntimeWarning: invalid value encountered in true_divide
  probs /= probs.sum()
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Code\Kaiyotech\ABAD\training\worker.py", line 122, in <module>
    RedisRolloutWorker(r,
  File "C:\Users\user\Code\Kaiyotech\ABAD\venv\lib\site-packages\rocket_learn\rollout_generator\redis_rollout_generator.py", line 573, in run
    versions = self._get_opponent_indices(n_new, n_old, pretrained_choice)
  File "C:\Users\user\Code\Kaiyotech\ABAD\venv\lib\site-packages\rocket_learn\rollout_generator\redis_rollout_generator.py", line 492, in _get_opponent_indices
    old_versions = np.random.choice(len(probs), size=n_old, p=probs, replace=n_new > 0).tolist()
  File "mtrand.pyx", line 935, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN

**Comment by Kaiyotech** [comment]
This got fixed somewhere along the way. Closing.
